---
- name: Make sure the namespace filebeat exists in the kubernetes cluster
  k8s:
    name: filebeat
    api_version: v1
    kind: Namespace
    state: present

- name: Configure filebeat with helm in filebeat namespace
  kubernetes.core.helm:
    name: filebeat
    namespace: filebeat
    chart_ref: elastic/filebeat
    chart_version: "{{ filebeat_version | default(omit) }}"

- name: check pod status of filebat 
  k8s_info:
    kind: Pod 
    namespace: filebeat
  register: pod_info
  retries: 5
  until:
    pod_info|json_query('resources[*].status.phase')|unique == ["Running"]
