---
- name: Create namespace {{ namespace }} in kubernetes cluster
  k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: devops

- name: Create secrets for devops
  k8s:
    state: present
    namespace: devops
    definition:
      apiVersion: v1 
      kind: Secret 
      metadata:
        name: my-secret
      stringData:
        username: admin
        password: 123456
        url: service.example.com
